#include <QLabel>
#include <QThread>
#include <QListWidget>
#include <QPushButton>
#include <QWidget>
#include <QFrame>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QApplication>
#include <Qt>
#include <QMenuBar>
#include <QMenu>
#include <QAction>
#include <QFileDialog>
#include <QObject>
#include <QDebug>
#include <QMetaObject>
#include <QVariant>
#include <QTableWidget>
#include <QTableWidgetItem>
#include <QDialog>
#include <QLineEdit>
#include <QComboBox>
#include <QColor>
#include <QHeaderView>
#include <QAbstractScrollArea>
#include <QStringList>
#include <QModelIndexList>
#include <QMessageBox>
#include <QIcon>
#include <QDoubleSpinBox>
#include <QProgressBar>
#include <QList>
#include <mutex>
#include <QDir>
#include <QPainter>
#include <QPainterPath>
#include <QMouseEvent>
#include <QFontDatabase>
#include <QSysInfo>

#include <vector>
#include <string>
#include <cstdlib>
#include <functional>
#include <iostream>
#include <algorithm>
#include <functional>
#include <cmath>
#include <fstream>
#include <sstream>
#include <filesystem>
#include <iomanip>
#include <cstdlib>
#include "../lib/rapidxml/rapidxml_utils.hpp"
